"""Initial schema migration

Revision ID: b911765d1455
Revises: 
Create Date: 2026-09-22 16:48:22.013874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.database


# revision identifiers, used by Alembic.
revision: str = 'b911765d1455'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_skills',
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('aliases', app.core.database.CompatibleJSON(), nullable=False),
    sa.Column('skill_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_skills_canonical_name'), 'custom_skills', ['canonical_name'], unique=True)
    op.create_table('taxonomy_occupations',
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_skills', app.core.database.CompatibleJSON(), nullable=False),
    sa.Column('optional_skills', app.core.database.CompatibleJSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxonomy_occupations_source_id'), 'taxonomy_occupations', ['source_id'], unique=False)
    op.create_index(op.f('ix_taxonomy_occupations_title'), 'taxonomy_occupations', ['title'], unique=False)
    op.create_table('taxonomy_skills',
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('aliases', app.core.database.CompatibleJSON(), nullable=False),
    sa.Column('skill_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', app.core.database.GUID(length=36), nullable=True),
    sa.Column('embedding', app.core.database.CompatibleJSON(), nullable=True),
    sa.Column('related_skills', app.core.database.CompatibleJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['taxonomy_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_taxonomy_canonical_lower', 'taxonomy_skills', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_taxonomy_skills_canonical_name'), 'taxonomy_skills', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_taxonomy_skills_source_id'), 'taxonomy_skills', ['source_id'], unique=False)
    op.create_table('users',
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('job_descriptions',
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('user_id', app.core.database.GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_json', app.core.database.CompatibleJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_user_id'), 'job_descriptions', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('user_id', app.core.database.GUID(length=36), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_json', app.core.database.CompatibleJSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('resume_id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('job_description_id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('matched_skills', app.core.database.CompatibleJSON(), nullable=False),
    sa.Column('missing_skills', app.core.database.CompatibleJSON(), nullable=False),
    sa.Column('weak_skills', app.core.database.CompatibleJSON(), nullable=False),
    sa.Column('related_partial_skills', app.core.database.CompatibleJSON(), nullable=False),
    sa.Column('extra_skills', app.core.database.CompatibleJSON(), nullable=False),
    sa.Column('gap_summary', app.core.database.CompatibleJSON(), nullable=False),
    sa.Column('scores', app.core.database.CompatibleJSON(), nullable=False),
    sa.Column('explanations', app.core.database.CompatibleJSON(), nullable=False),
    sa.Column('provenance', app.core.database.CompatibleJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_job_description_id'), 'analysis_results', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_resume_id'), 'analysis_results', ['resume_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('analysis_result_id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('interview_plan', app.core.database.CompatibleJSON(), nullable=True),
    sa.Column('generated_questions', app.core.database.CompatibleJSON(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('summary_feedback', app.core.database.CompatibleJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_analysis_result_id'), 'interview_sessions', ['analysis_result_id'], unique=False)
    op.create_table('interview_answers',
    sa.Column('id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('interview_session_id', app.core.database.GUID(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('evaluation_json', app.core.database.CompatibleJSON(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_answers_interview_session_id'), 'interview_answers', ['interview_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_answers_interview_session_id'), table_name='interview_answers')
    op.drop_table('interview_answers')
    op.drop_index(op.f('ix_interview_sessions_analysis_result_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_analysis_results_resume_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_job_description_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_job_descriptions_user_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_taxonomy_skills_source_id'), table_name='taxonomy_skills')
    op.drop_index(op.f('ix_taxonomy_skills_canonical_name'), table_name='taxonomy_skills')
    op.drop_index('idx_taxonomy_canonical_lower', table_name='taxonomy_skills')
    op.drop_table('taxonomy_skills')
    op.drop_index(op.f('ix_taxonomy_occupations_title'), table_name='taxonomy_occupations')
    op.drop_index(op.f('ix_taxonomy_occupations_source_id'), table_name='taxonomy_occupations')
    op.drop_table('taxonomy_occupations')
    op.drop_index(op.f('ix_custom_skills_canonical_name'), table_name='custom_skills')
    op.drop_table('custom_skills')
    # ### end Alembic commands ###
