import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { createInterview } from '../api/client';
import { ScoreCard } from '../components/ScoreCard';
import { SkillGapBadge } from '../components/SkillGapBadge';
import { LoadingSpinner } from '../components/LoadingSpinner';
import {
  CheckCircle2,
  AlertTriangle,
  XCircle,
  ArrowRightLeft,
  ArrowRight,
  Sparkles,
  Zap,
  Layers,
  GraduationCap,
  Key,
  ShieldCheck,
  Play
} from 'lucide-react';

export const AnalysisViewPage: React.FC = () => {
  const { analysis, interview, setInterview, setStep } = useApp();
  const [loadingInterview, setLoadingInterview] = useState(false);
  const [difficulty, setDifficulty] = useState('medium');
  const [questionCount, setQuestionCount] = useState(8);

  if (!analysis) {
    return (
      <div className="max-w-4xl mx-auto py-12 text-center text-slate-500">
        No analysis data available. Please upload a resume and select a target role first.
      </div>
    );
  }

  const scores = analysis.scores;
  const gap = analysis.gap_summary;

  const handleStartInterview = async () => {
    // If interview is already pre-generated by role-fit analysis, navigate immediately
    if (interview && interview.generated_questions && interview.generated_questions.length > 0) {
      setStep('interview');
      return;
    }

    setLoadingInterview(true);
    try {
      const session = await createInterview({
        analysisId: analysis.id,
        questionCount,
        difficulty,
      });
      setInterview(session);
      setStep('interview');
    } catch (err) {
      console.error(err);
      alert('Failed to launch mock interview session.');
    } finally {
      setLoadingInterview(false);
    }
  };

  const getReadinessBanner = (r: string) => {
    switch (r) {
      case 'high':
        return {
          bg: 'bg-emerald-50 border-emerald-200 text-emerald-900',
          badge: 'bg-emerald-600 text-white',
          label: 'High Readiness',
          desc: 'Strong match with core job requirements and verifiable experience.'
        };
      case 'low':
        return {
          bg: 'bg-rose-50 border-rose-200 text-rose-900',
          badge: 'bg-rose-600 text-white',
          label: 'Low Readiness',
          desc: 'Critical mandatory requirements are currently missing from the resume.'
        };
      case 'moderate':
      default:
        return {
          bg: 'bg-amber-50 border-amber-200 text-amber-900',
          badge: 'bg-amber-600 text-white',
          label: 'Moderate Readiness',
          desc: 'Solid foundations with transferable skills; gaps exist in specialized tooling.'
        };
    }
  };

  const banner = getReadinessBanner(gap.overall_readiness);

  return (
    <div className="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8 space-y-8">
      {/* Header & Target Role */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <span className="text-xs font-bold text-blue-600 uppercase tracking-wider">
            Step 3 of 5 • Explainable Evaluation
          </span>
          <h2 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight">
            Skill Gap & Fit Analysis: {analysis.target_role}
          </h2>
          <p className="text-xs text-slate-500 mt-1">
            Deterministic mapping against canonical ESCO & O*NET taxonomy with verified citations.
          </p>
        </div>

        <div className="flex items-center space-x-3 bg-white p-3 rounded-2xl border border-slate-200 shadow-sm">
          <div className="text-right">
            <div className="text-xs text-slate-400 font-bold uppercase">Overall Match Score</div>
            <div className="text-3xl font-black text-slate-900">{Math.round(scores.overall_score)}/100</div>
          </div>
          <div className="w-12 h-12 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center font-bold text-sm border-2 border-blue-200">
            {Math.round(scores.overall_score)}%
          </div>
        </div>
      </div>

      {/* Executive Gap Summary Banner */}
      <div className={`p-6 rounded-2xl border ${banner.bg} shadow-sm space-y-3`}>
        <div className="flex items-center justify-between">
          <span className={`text-xs font-bold uppercase px-3 py-1 rounded-full ${banner.badge}`}>
            {banner.label}
          </span>
          <span className="text-xs text-slate-500 font-medium">
            AI Talent Engine Assessment
          </span>
        </div>

        <p className="text-sm font-medium leading-relaxed">
          {gap.narrative_summary}
        </p>

        {gap.critical_missing_skills.length > 0 && (
          <div className="pt-2 flex flex-wrap items-center gap-2 text-xs">
            <span className="font-bold text-slate-700">Critical Missing Requirements:</span>
            {gap.critical_missing_skills.map((s, idx) => (
              <span key={idx} className="bg-white/80 border border-rose-300 text-rose-800 font-semibold px-2.5 py-0.5 rounded-full">
                {s}
              </span>
            ))}
          </div>
        )}
      </div>

      {/* 5-Factor Explainable Scoring Cards */}
      <div>
        <h3 className="text-sm font-bold text-slate-700 uppercase tracking-wider mb-4 flex items-center">
          <Layers className="w-4 h-4 mr-2 text-blue-600" />
          5-Factor Explainable Scoring Breakdown
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-4">
          <ScoreCard
            title="Skill Match"
            scoreData={scores.skill_match_score}
            icon={<Zap className="w-4 h-4 text-amber-500" />}
          />
          <ScoreCard
            title="Experience Alignment"
            scoreData={scores.experience_score}
            icon={<GraduationCap className="w-4 h-4 text-blue-500" />}
          />
          <ScoreCard
            title="Project Quality"
            scoreData={scores.project_score}
            icon={<Layers className="w-4 h-4 text-purple-500" />}
          />
          <ScoreCard
            title="Keyword Coverage"
            scoreData={scores.keyword_score}
            icon={<Key className="w-4 h-4 text-emerald-500" />}
          />
          <ScoreCard
            title="Seniority Match"
            scoreData={scores.seniority_score}
            icon={<ShieldCheck className="w-4 h-4 text-indigo-500" />}
          />
        </div>
      </div>

      {/* 4-Way Skill Matrix */}
      <div>
        <h3 className="text-sm font-bold text-slate-700 uppercase tracking-wider mb-4 flex items-center">
          <Zap className="w-4 h-4 mr-2 text-blue-600" />
          Taxonomy Skill Matrix & Evidence (Click any skill to view citation)
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {/* Matched */}
          <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-sm">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100 mb-3">
              <span className="font-bold text-xs text-slate-900 flex items-center">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 mr-1.5" />
                Matched ({analysis.matched_skills.length})
              </span>
              <span className="text-[10px] bg-emerald-100 text-emerald-800 font-bold px-1.5 py-0.5 rounded">
                Full Credit
              </span>
            </div>
            {analysis.matched_skills.length === 0 ? (
              <p className="text-xs text-slate-400 italic">No direct matches</p>
            ) : (
              analysis.matched_skills.map((item, idx) => (
                <SkillGapBadge key={idx} item={item} />
              ))
            )}
          </div>

          {/* Weak */}
          <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-sm">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100 mb-3">
              <span className="font-bold text-xs text-slate-900 flex items-center">
                <AlertTriangle className="w-4 h-4 text-amber-600 mr-1.5" />
                Weak Evidence ({analysis.weak_skills.length})
              </span>
              <span className="text-[10px] bg-amber-100 text-amber-800 font-bold px-1.5 py-0.5 rounded">
                Partial Credit
              </span>
            </div>
            {analysis.weak_skills.length === 0 ? (
              <p className="text-xs text-slate-400 italic">No weak skills</p>
            ) : (
              analysis.weak_skills.map((item, idx) => (
                <SkillGapBadge key={idx} item={item} />
              ))
            )}
          </div>

          {/* Transferable */}
          <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-sm">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100 mb-3">
              <span className="font-bold text-xs text-slate-900 flex items-center">
                <ArrowRightLeft className="w-4 h-4 text-indigo-600 mr-1.5" />
                Transferable ({analysis.related_partial_skills.length})
              </span>
              <span className="text-[10px] bg-indigo-100 text-indigo-800 font-bold px-1.5 py-0.5 rounded">
                Transferable
              </span>
            </div>
            {analysis.related_partial_skills.length === 0 ? (
              <p className="text-xs text-slate-400 italic">No transferable bridges</p>
            ) : (
              analysis.related_partial_skills.map((item, idx) => (
                <SkillGapBadge key={idx} item={item} />
              ))
            )}
          </div>

          {/* Missing */}
          <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-sm">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100 mb-3">
              <span className="font-bold text-xs text-slate-900 flex items-center">
                <XCircle className="w-4 h-4 text-rose-600 mr-1.5" />
                Missing ({analysis.missing_skills.length})
              </span>
              <span className="text-[10px] bg-rose-100 text-rose-800 font-bold px-1.5 py-0.5 rounded">
                Zero Credit
              </span>
            </div>
            {analysis.missing_skills.length === 0 ? (
              <p className="text-xs text-slate-400 italic">No missing requirements</p>
            ) : (
              analysis.missing_skills.map((item, idx) => (
                <SkillGapBadge key={idx} item={item} />
              ))
            )}
          </div>
        </div>
      </div>

      {/* Quick Wins & Recommended Focus Areas */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {gap.quick_wins && gap.quick_wins.length > 0 && (
          <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm">
            <h3 className="text-sm font-bold text-slate-900 mb-3 flex items-center">
              <Sparkles className="w-4 h-4 text-blue-600 mr-2" />
              Immediate Actionable Quick Wins
            </h3>
            <ul className="space-y-2 text-xs">
              {gap.quick_wins.map((win, idx) => (
                <li key={idx} className="bg-slate-50 p-2.5 rounded-xl border border-slate-100 flex items-start">
                  <span className="font-bold text-blue-600 mr-2 text-sm">✓</span>
                  <span className="text-slate-700 leading-relaxed">{win}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {gap.recommended_focus_areas && gap.recommended_focus_areas.length > 0 && (
          <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm">
            <h3 className="text-sm font-bold text-slate-900 mb-3 flex items-center">
              <Zap className="w-4 h-4 text-amber-500 mr-2" />
              Recommended Focus Areas to Bridge Gaps
            </h3>
            <div className="flex flex-wrap gap-2 text-xs">
              {gap.recommended_focus_areas.map((area, idx) => (
                <span key={idx} className="bg-amber-50 border border-amber-200 text-amber-900 font-semibold px-3 py-1.5 rounded-xl flex items-center">
                  <span className="w-1.5 h-1.5 rounded-full bg-amber-500 mr-2"></span>
                  {area}
                </span>
              ))}
            </div>
            <p className="text-[11px] text-slate-500 mt-3 leading-relaxed">
              These competencies will accelerate your readiness rating from <b>{gap.overall_readiness.toUpperCase()}</b> to candidate excellence.
            </p>
          </div>
        )}
      </div>

      {/* Launch Mock Interview Section */}
      <div className="bg-gradient-to-r from-blue-900 via-indigo-900 to-slate-900 text-white rounded-2xl p-6 sm:p-8 shadow-xl">
        <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6">
          <div>
            <span className="inline-flex items-center text-xs font-bold uppercase tracking-wider px-3 py-1 rounded-full bg-blue-500/30 text-blue-200 border border-blue-400/30 mb-2">
              Next Stage • Dynamic AI Mock Interview
            </span>
            <h3 className="text-xl sm:text-2xl font-black tracking-tight">
              Ready to Practice With Resume-Specific Interview Questions?
            </h3>
            <p className="text-xs text-blue-200 mt-1 max-w-2xl">
              Generates 7–10 rigorous, dynamic interview questions targeting your specific projects,
              experience bullets, and identified missing skills. No generic question templates.
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-3 w-full lg:w-auto">
            <div>
              <label className="block text-[10px] uppercase font-bold text-blue-300 mb-1">Difficulty</label>
              <select
                value={difficulty}
                onChange={(e) => setDifficulty(e.target.value)}
                className="bg-slate-800 text-white border border-slate-700 text-xs rounded-lg px-3 py-2"
              >
                <option value="easy">Easy</option>
                <option value="medium">Medium</option>
                <option value="hard">Hard</option>
              </select>
            </div>

            <div>
              <label className="block text-[10px] uppercase font-bold text-blue-300 mb-1">Questions</label>
              <select
                value={questionCount}
                onChange={(e) => setQuestionCount(Number(e.target.value))}
                className="bg-slate-800 text-white border border-slate-700 text-xs rounded-lg px-3 py-2"
              >
                <option value={6}>6 Questions</option>
                <option value={8}>8 Questions</option>
                <option value={10}>10 Questions</option>
              </select>
            </div>

            <div className="self-end pt-3">
              <button
                disabled={loadingInterview}
                onClick={handleStartInterview}
                className="bg-blue-500 hover:bg-blue-400 text-slate-950 font-bold text-xs px-6 py-2.5 rounded-xl shadow-lg transition-all flex items-center disabled:opacity-50"
              >
                {loadingInterview ? (
                  <span>Generating Interview...</span>
                ) : (
                  <>
                    <Play className="w-4 h-4 mr-1.5 fill-current" />
                    <span>Launch Mock Interview</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
